[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "resume-screening"
version = "1.0.0"
description = "Automated Resume Screening using Machine Learning"

[project.scripts]
app = "wsgi:app"

[tool.vercel]
runtime = "python3.11"
